# +-------------------------------------------------------------------+
# | Copyright IBM Corp. 2025 All Rights Reserved                      |
# | PID 5698-SPR                                                      |
# +-------------------------------------------------------------------+
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: spyre-ca-issuer
  namespace: "FILLED BY THE OPERATOR"
spec:
  ca:
    secretName: root-ca-secret
