# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
#
#  This file is an example for minimum specification,
#  which has no optional components and no experimental modes enabled.
#
apiVersion: spyre.ibm.com/v1alpha1
kind: SpyreClusterPolicy
metadata:
  name: spyreclusterpolicy
spec:
  devicePlugin:
    repository: "docker.io/spyre-operator"
    image: "spyre-device-plugin"
    version: 1.4.0-dev
