# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
#
#  Remarks:
#   This sample SpyreClusterPolicy contains some images built only for x86 architecture.
#   To enable card management and metrics exporter, please make sure to update the image for your architecture.
#
#   .spec.devicePlugin.initContainer is currently available for x86 architecture.
#   Please remove the initContainer section for unsupported architecture.
#
apiVersion: spyre.ibm.com/v1alpha1
kind: SpyreClusterPolicy
metadata:
  name: spyreclusterpolicy
spec:
  experimentalMode:
  - perDeviceAllocation
  - topologyAwareAllocation
  - externalDeviceReservation
  devicePlugin:
    repository: "docker.io/spyre-operator"
    image: "spyre-device-plugin"
    version: 1.4.0-dev
    configPath: /etc/aiu
    configName: senlib_config.json
    initContainer:
      repository: "docker.io/spyre-operator"
      image: "spyre-device-plugin-init"
      version: 1.4.0-dev
      executePolicy: IfNotPresent
  scheduler:
    repository: "docker.io/spyre-operator"
    image: "spyre-scheduler"
    version: 1.4.0-dev
  podValidator:
    enabled: true
    repository: "docker.io/spyre-operator"
    image: "spyre-webhook-validator"
    version: 1.4.0-dev
  metricsExporter:
    enabled: false
    repository: "docker.io/spyre-operator"
    image: "spyre-exporter"
    version: 1.4.0-dev
  healthChecker:
    enabled: false
    repository: "docker.io/spyre-operator"
    image: "spyre-health-checker"
    version: 1.4.0-dev
