# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dra-driver-spyre
  namespace: "FILLED BY THE OPERATOR"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - spyre-operator-nonroot
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
