# +-------------------------------------------------------------------+
# | Copyright IBM Corp. 2025 All Rights Reserved                      |
# | PID 5698-SPR                                                      |
# +-------------------------------------------------------------------+

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dra-driver-spyre
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - spyre-operator-nonroot
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "resource.k8s.io"
  resources:
  - resourceclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "resource.k8s.io"
  resources:
  - resourceslices
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
