/*
 * +-------------------------------------------------------------------+
 * | Copyright (c) 2025, 2026 IBM Corp.                                |
 * | SPDX-License-Identifier: Apache-2.0                               |
 * +-------------------------------------------------------------------+
 */

package spyreconst

const (
	// environment variable keys
	// DeviceConfigOutputPathKey defines container-specific device config output path at each container
	DeviceConfigOutputPathKey = "CONFIG_FILEPATH"
	// DeviceConfigFileNameKey defines device config file path
	DeviceConfigFileNameKey = "CONFIG_FILENAME"
	// MetricsContainerPathKey defines metrics file path at each container
	MetricsContainerPathKey = "SPYRE_METRIC_FILEPATH"
	// MetricsExportKey defines whether metric exporter enabled (true) or disabled (false)
	MetricsExportKey = "SPYRE_METRIC_EXPORT"
	// SpyreHealthSocketEnvKey defines socket path of health checker service
	SpyreHealthSocketEnvKey = "SPYRE_HEALTH_SOCK"

	// label keys
	// CommonSpyreLabelKey: operator-applied when NFD detects card (or pseudo mode). Used by DaemonSets to schedule.
	CommonSpyreLabelKey    = "ibm.com/spyre.present"
	SpyreNodeRoleLabelKey  = "node-role.kubernetes.io/spyre" // admin-applied for MachineConfig/MCP; operator does not set this
	SpyreProductLabelKey   = "ibm.com/spyre.product"
	SpyreCountLabelKey     = "ibm.com/spyre.count"
	SpyreMachineLabelKey   = "ibm.com/spyre.machine"
	OpenShiftMonitoringKey = "openshift.io/cluster-monitoring"
	SpyreMonitoringIDKey   = "ibm.com/spyre.monitoring_id"

	// webhook failure label keys
	MonitorResourcesFailedKey        = "spyre-monitoring-resource-failed"
	SpyreEmbedAnnotationFailedKey    = "spyre-embed-annotation-failed"
	MonitorSidecarInjectionFailedKey = "spyre-monitoring-sidecar-injection-failed"

	// CardManagementLabelKey and CardManagementLabelValue is the label of
	// the card management Pod.
	// This must be equals to the one defined in
	// `assets/state-plugin-components/spyre-card-management/0600_deployment.yaml`.
	CardManagementLabelKey   = "app"
	CardManagementLabelValue = "cardmgmt"
	// CardManagementRunnerLabelKey and CardManagementRunnerLabelValue is the
	// label of Pf/Vf runner Pods.
	// This must be equals to the one defined in
	// `src/container_kube.py` of cardmgmt repository.
	CardManagementRunnerLabelKey   = "aiucardmanager"
	CardManagementRunnerLabelValue = "1"

	// optional component names
	HealthCheckerResourceName  = "spyre-health-checker"
	ValidatorResourceName      = "spyre-webhook-validator"
	DevicePluginResourceName   = "spyre-device-plugin"
	DRADriverResourceName      = "spyre-dra-driver"
	SchedulerResourceName      = "secondary-scheduler"
	CardManagementResourceName = "spyre-card-management"
	MonitorResourceName        = "spyre-metrics-exporter"

	ValidValue   = "true"
	InvalidValue = "false"
	ExistValue   = ""

	// resource names
	ResourcePrefix             = "ibm.com"
	PfResourceName             = "spyre_pf"
	VfResourceName             = "spyre_vf"
	ObsoletePfResourceName     = "aiu_pf"
	ObsoleteVfResourceName     = "aiu_vf"
	TierZeroResourceNameSuffix = "_tier0"
	TierOneResourceNameSuffix  = "_tier1"
	TierTwoResourceNameSuffix  = "_tier2"

	// experimental mode
	ModeEnabledValue = "1"

	// config names
	SpyreConfigVolumeMountName = "config"
	MonitorDataVolumeName      = "monitor-data"
	SenlibConfigTmplName       = "senlib-config-template"
	MonitorDataVolumeMountPath = "/data"
	MonitorPortName            = "spyre-metrics"
	DefaultMonitorPort         = int32(8082)
	MonitorContainerName       = "spyre-monitor"
	// constants regarding card management source
	CardManagementClaimName  = "cardmgmt"
	CardManagementConfigName = "spyre-cardmgmt-config"
	CardManagementConfigFile = "aiucardmgmt.ini"

	// config paths
	DefaultSenlibConfigFilename = "senlib_config.json"

	// DefaultTopologyFolder uses for mounting topology config map to device plugin pod.
	DefaultTopologyFolder = "/etc/aiu/topology"

	// ExporterPortKey must be the same as defined in exporter.py for reflecting `METRICS.general.port` in senlib_config template
	ExporterPortKey = "MONITOR_PORT"
	// ExporterPollingKey  must be the same as defined in exporter.py for reflecting `METRICS.general.promclient.wakeup_interval_in_seconds` in senlib_config template
	ExporterPollingKey = "POLL_INTERVAL_SEC"
	// CardManagementEnabledKey
	CardManagementEnabledKey = "CARD_MANAGEMENT_ENABLED"
	// IgnoreMetadataKey must be set to device plugin container to ignore topo.json in metadata generated by external init container
	// This will be automatically set to true if the init container is not set.
	IgnoreMetadataKey = "IGNORE_EXTERNAL_METADATA"
	// P2PDMAKey must be set to device plugin and its init container (if applicable) to enable P2P DMA protocol discovery (if applicable) and the configuration
	P2PDMAKey = "P2PDMA"

	// WebhookGuardWaitTimeInSec is a wait time in sec before retry to guard conflict pod creation request
	// The specified duration should cover the sync time between different resource pool after allocation.
	WebhookGuardWaitTimeInSec = 10

	// Constant "true" string
	TRUE = "true"

	// Constant "false" string
	FALSE = "false"

	// Constant for strings filled by operator
	OPERATOR_FILLED         = "FILLED BY THE OPERATOR"
	FILTER_OPERATOR_FILLED  = "FILTER BY THE OPERATOR"
	PFIMAGE_OPERATOR_FILLED = "PFIMAGE BY THE OPERATOR"
	VFIMAGE_OPERATOR_FILLED = "VFIMAGE BY THE OPERATOR"

	// scheduler integration
	SpyreSchedulerName = "spyre-scheduler"
)
