# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: spyre-device-plugin
    tier: node
  name: spyre-device-plugin
  namespace: "FILLED BY THE OPERATOR"
  annotations:
    openshift.io/scc: spyre-operator-nonroot
spec:
  selector:
    matchLabels:
      app: spyre-device-plugin
  template:
    metadata:
      labels:
        app: spyre-device-plugin
    spec:
      initContainers:
      - name: init-data
        image: "FILLED BY THE OPERATOR"
        securityContext:
          runAsUser: 1001
          runAsGroup: 0
          runAsNonRoot: true
          privileged: false
          seLinuxOptions:
            type: spc_t
        env:
        - name: VERIFY_P2P
          value: "0"
        - name: FLEX_COMPUTE
          value: SENTIENT
        - name: FLEX_DEVICE
          value: VFIO
        - name: DTLOG_LEVEL
          value: "error"
        - name: TORCH_SENDNN_LOG
          value: "CRITICAL"
        - name: DT_DEEPRT_VERBOSE
          value: "-1"
        volumeMounts:
        - name: device-plugin-config
          mountPath: /usr/local/etc/device-plugins
          readOnly: false
      nodeSelector:
        ibm.com/spyre.present: "true"
      tolerations:
      - key: ibm.com/spyre
        operator: Exists
        effect: NoSchedule
      priorityClassName: system-node-critical
      serviceAccount: spyre-device-plugin
      containers:
      - name: spyre-device-plugin
        image: "FILLED BY THE OPERATOR"
        imagePullPolicy: Always
        args: []
        securityContext:
          runAsUser: 1001
          runAsGroup: 0
          runAsNonRoot: true
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
            ephemeral-storage: 2M
          requests:
            cpu: 10m
            memory: 128Mi
            ephemeral-storage: 1M
        ports:
        - name: probes
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/
          readOnly: false
        - name: log
          mountPath: /var/log
        - name: config-volume
          mountPath: /etc/aiu
        - name: device-plugin-config
          mountPath: /usr/local/etc/device-plugins
          readOnly: false
        - name: senlib-config-template
          mountPath: "/etc/senlib-config-template"
        - name: spyre-device-plugin-cert
          mountPath: /etc/device-plugin/certs
          readOnly: true
        - name: crio-socket
          mountPath: /var/run/crio/crio.sock
        - name: cardmgmt-local
          mountPath: /var/cardmgmt/ibm/spyre
        env:
        - name: SPYRE_HEALTH_SOCK
          value: /usr/local/etc/device-plugins/spyre-sockets/health-checker.sock
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: devicesock
        hostPath:
          path: /var/lib/kubelet/
      - name: log
        hostPath:
          path: /var/log
      - name: config-volume
        configMap:
          name: spyre-config
      - name: device-plugin-config
        hostPath:
          path: /usr/local/etc/device-plugins
          type: DirectoryOrCreate
      - name: senlib-config-template
        configMap:
          name: senlib-config-template
      - name: spyre-device-plugin-cert
        secret:
          secretName: spyre-device-plugin-cert
          optional: true
      - name: crio-socket
        hostPath:
          path: /var/run/crio/crio.sock
      - name: cardmgmt-local
        hostPath:
          path: /var/cardmgmt/ibm/spyre
          type: DirectoryOrCreate
