# Copyright (c) 2025, 2026 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

resources:
- bases/spyre-operator.clusterserviceversion.yaml
- ../default
- ../scorecard

replacements:
- source:
    kind: Deployment
    name: spyre-operator
    fieldPath: spec.template.spec.containers.[name=manager].image
  targets:
  - select:
      kind: ClusterServiceVersion
      name: spyre-operator.v0.0.0
    fieldPaths:
    - metadata.annotations.containerImage
